### ISSUE TITLE
[FEATURE] Kotlin

### ISSUE THREAD

**Issue by sourTaste000** [corby-dev/corby#34]
**Is your feature request related to a problem? Please describe.**
No

**Describe your feature.**
kotlin better

**Describe the solution you'd like**
port everything into kotlin

**Describe alternatives you've considered**
Use rust instead

**Additional context**
Bottom Text

**Comment by d1snin** [comment]
I have no idea how to write anything in Kotlin and will study Kotlin after learning Spring, algorithms and data structures, so I will start learning it in about 3 months

**Comment by ZimnyCat** [comment]
> kotlin better

no

**Comment by ToxicAven** [comment]
> > kotlin better
> 
> no

But it clearly is. :trolleybus:

**Comment by d1snin** [comment]
^

**Comment by sourTaste000** [comment]
pogger

**Comment by d1snin** [comment]
:sunglasses:
